// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBafe5d40DecodeGithubComSTurchinskiyLoyaltySystemInternalModels(in *jlexer.Lexer, out *AccrualData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "order":
			out.Order = string(in.String())
		case "status":
			out.Status = AccrualStatus(in.Int())
		case "accrual":
			out.Accrual = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBafe5d40EncodeGithubComSTurchinskiyLoyaltySystemInternalModels(out *jwriter.Writer, in AccrualData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix[1:])
		out.String(string(in.Order))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.Int(int(in.Status))
	}
	if in.Accrual != 0 {
		const prefix string = ",\"accrual\":"
		out.RawString(prefix)
		out.Float64(float64(in.Accrual))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccrualData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBafe5d40EncodeGithubComSTurchinskiyLoyaltySystemInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccrualData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBafe5d40EncodeGithubComSTurchinskiyLoyaltySystemInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccrualData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBafe5d40DecodeGithubComSTurchinskiyLoyaltySystemInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccrualData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBafe5d40DecodeGithubComSTurchinskiyLoyaltySystemInternalModels(l, v)
}
